# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3ac1d2a9e620c1d9c82f36d96ec7deb9"
name = "qrcode"
handle = "qrcode-194"
application_url = "https://sp-administrators-michelle-tent.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-3749937e.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sp-administrators-michelle-tent.trycloudflare.com/auth/callback",
  "https://sp-administrators-michelle-tent.trycloudflare.com/auth/shopify/callback",
  "https://sp-administrators-michelle-tent.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
